// ─────────────────────────────────────────────────
// DesignScorePanel Styles — Dark Theme
// ─────────────────────────────────────────────────

import type React from 'react';

export const designScorePanelStyles: Record<string, React.CSSProperties> = {
    root: {
        width: 260,
        background: '#13161b',
        borderLeft: '1px solid #1e232e',
        padding: 14,
        display: 'flex',
        flexDirection: 'column',
        gap: 10,
        color: '#e0e0e0',
        fontFamily: 'Inter, system-ui, sans-serif',
        fontSize: 12,
        overflowY: 'auto',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    title: {
        fontSize: 13,
        fontWeight: 600,
        letterSpacing: -0.3,
        color: '#f0f0f0',
    },
    closeBtn: {
        background: 'none',
        border: 'none',
        color: '#666',
        cursor: 'pointer',
        fontSize: 14,
        padding: '2px 6px',
        borderRadius: 4,
    },
    scoreCard: {
        display: 'flex',
        alignItems: 'center',
        gap: 14,
        background: '#1a1d24',
        borderRadius: 10,
        padding: '14px 16px',
    },
    scoreRing: {
        width: 52,
        height: 52,
        borderRadius: '50%',
        border: '3px solid',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 20,
        fontWeight: 800,
        flexShrink: 0,
    },
    scoreInfo: {
        flex: 1,
    },
    gradeLabel: {
        fontSize: 16,
        fontWeight: 700,
    },
    scoreMeta: {
        fontSize: 10,
        color: '#888',
        marginTop: 3,
    },
    fixAllBtn: {
        padding: '9px 0',
        background: '#2563eb',
        border: 'none',
        borderRadius: 6,
        color: '#fff',
        fontSize: 11,
        fontWeight: 600,
        cursor: 'pointer',
        transition: 'background 0.15s',
        letterSpacing: 0.2,
    },
    section: {
        display: 'flex',
        flexDirection: 'column',
        gap: 0,
    },
    sectionToggle: {
        background: 'none',
        border: 'none',
        color: '#888',
        cursor: 'pointer',
        fontSize: 10,
        textTransform: 'uppercase' as const,
        letterSpacing: 0.8,
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '6px 0',
    },
    issueRow: {
        display: 'flex',
        gap: 8,
        padding: '8px 0',
        borderTop: '1px solid #1e232e',
    },
    severityDot: {
        width: 18,
        height: 18,
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 9,
        fontWeight: 800,
        color: '#13161b',
        flexShrink: 0,
        marginTop: 1,
    },
    issueContent: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        gap: 3,
    },
    issueCatRow: {
        display: 'flex',
        gap: 6,
        alignItems: 'center',
    },
    catBadge: {
        padding: '1px 5px',
        borderRadius: 3,
        fontSize: 8,
        fontWeight: 700,
        letterSpacing: 0.5,
    },
    fixableBadge: {
        padding: '1px 5px',
        borderRadius: 3,
        fontSize: 8,
        fontWeight: 600,
        background: '#2563eb20',
        color: '#60a5fa',
    },
    issueMsg: {
        fontSize: 11,
        color: '#bbb',
        lineHeight: 1.4,
    },
    issueElement: {
        fontSize: 9,
        color: '#666',
    },
    tip: {
        padding: '6px 8px',
        fontSize: 10,
        color: '#999',
        borderLeft: '2px solid #2563eb40',
        lineHeight: 1.5,
        marginTop: 4,
    },
    allClear: {
        textAlign: 'center',
        color: '#4ade80',
        padding: '24px 0',
        fontSize: 12,
        fontWeight: 500,
    },
    badge: {
        width: 32,
        height: 32,
        borderRadius: '50%',
        border: '2px solid',
        background: '#13161b',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 11,
        fontWeight: 800,
        cursor: 'pointer',
        padding: 0,
        transition: 'transform 0.15s',
    },
};
