// ─────────────────────────────────────────────────
// AboutPage — Company information for Google Ads API compliance
// ─────────────────────────────────────────────────

import { useNavigate, Link } from 'react-router-dom';
import { GlidLogo } from '@/components/brand/GlidLogo';
import './legal.css';

export function AboutPage() {
    const navigate = useNavigate();

    return (
        <div className="legal-page">
            <header className="legal-header">
                <div className="legal-header-inner">
                    <div className="legal-logo" onClick={() => navigate('/')} role="button" tabIndex={0}>
                        <GlidLogo size={22} variant="white" />
                    </div>
                    <nav className="legal-nav">
                        <Link to="/">Home</Link>
                        <Link to="/privacy">Privacy</Link>
                        <Link to="/terms">Terms</Link>
                    </nav>
                </div>
            </header>

            <main className="legal-content">
                <h1>About ACE</h1>

                <section className="legal-section">
                    <h2>Our Mission</h2>
                    <p>
                        ACE (Automated Creative Engine) is a full creative platform built for modern marketing teams.
                        We empower agencies, brands, and in-house creative departments to design, manage, and deploy
                        digital advertising creatives at scale — from display banners and social media posts to
                        video ads and rich media experiences.
                    </p>
                    <p>
                        Our mission is to eliminate the repetitive, manual work in creative production so teams can
                        focus on what matters: strategy, storytelling, and performance.
                    </p>
                </section>

                <section className="legal-section">
                    <h2>What We Do</h2>
                    <ul>
                        <li>
                            <strong>AI-Powered Design Engine</strong> — Generate professional-grade creatives using
                            natural language prompts. Our AI agent understands layout composition, typography, and
                            brand guidelines to produce publish-ready designs in seconds.
                        </li>
                        <li>
                            <strong>Smart Sizing</strong> — Design once on a master canvas. ACE automatically generates
                            correctly proportioned variants for every ad format — 300x250, 728x90, 160x600, 1080x1080,
                            and dozens more — with intelligent text reflow and constraint-based positioning.
                        </li>
                        <li>
                            <strong>Campaign Integration</strong> — Push finalized creatives directly to advertising
                            platforms including Google Ads, Meta Ads, and programmatic networks. Pull performance
                            data back into ACE for creative optimization.
                        </li>
                        <li>
                            <strong>Brand Kit Management</strong> — Upload logos, define color palettes, and set
                            typography standards. Every creative generated by ACE respects your brand guidelines
                            automatically.
                        </li>
                        <li>
                            <strong>Template Library</strong> — Start from professionally designed templates or save
                            your own. Admins can customize templates globally for consistent brand output across
                            the entire organization.
                        </li>
                    </ul>
                </section>

                <section className="legal-section">
                    <h2>Our Team</h2>
                    <p>
                        ACE is built by a team of engineers and designers with deep experience in ad-tech, creative
                        tooling, and machine learning. Based in Toronto, Canada, we are dedicated to building the
                        most powerful and intuitive creative platform for the advertising industry.
                    </p>
                </section>

                <section className="legal-section">
                    <h2>Contact</h2>
                    <div className="legal-contact-grid">
                        <div className="legal-contact-item">
                            <h3>General Inquiries</h3>
                            <a href="mailto:hello@glid.ai">hello@glid.ai</a>
                        </div>
                        <div className="legal-contact-item">
                            <h3>Sales</h3>
                            <a href="mailto:sales@glid.ai">sales@glid.ai</a>
                        </div>
                        <div className="legal-contact-item">
                            <h3>Office</h3>
                            <address>
                                50 Power Street<br />
                                Toronto, Ontario M5A 0V3<br />
                                Canada
                            </address>
                        </div>
                    </div>
                </section>
            </main>

            <footer className="legal-footer">
                <span>&copy; {new Date().getFullYear()} Glid Technologies Inc. All rights reserved.</span>
                <span className="legal-footer-address">50 Power St, Toronto, ON M5A 0V3, Canada</span>
            </footer>
        </div>
    );
}
